version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    volumes:
      - ./user-service:/var/www
    ports:
      - "8001:9000"
    networks:
      - app-network

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
