version: '3.8'

services:
  user-service:
    image: restaurant-app/user-service
    build:
      context: ./user-service
    container_name: user-service
    volumes:
      - ./user-service:/var/www
    ports:
      - "8001:8001"
    networks:
      - app-network
    depends_on:
      - rabbitmq

  restaurant-service:
    image: restaurant-app/restaurant-service
    build:
      context: ./restaurant-service
    container_name: restaurant-service
    volumes:
      - ./restaurant-service:/var/www
    ports:
      - "8002:8002"
    networks:
      - app-network
    depends_on:
      - rabbitmq

  booking-service:
    image: restaurant-app/booking-service
    build:
      context: ./booking-service
    container_name: booking-service
    volumes:
      - ./booking-service:/var/www
    ports:
      - "8003:8003"
    networks:
      - app-network
    depends_on:
      - rabbitmq

  chat-service:
    image: restaurant-app/chat-service
    build:
      context: ./chat-service
    container_name: chat-service
    volumes:
      - ./chat-service:/var/www
    ports:
      - "8004:8004"
      - "6001:8080"
    networks:
      - app-network
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  frontend-service:
    image: restaurant-app/frontend-service
    build:
      context: ./frontend-service
    container_name: frontend-service
    volumes:
      - ./frontend-service:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - api-gateway

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
      - restaurant-service
      - booking-service
      - chat-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
