name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

env:
  IMAGE_PREFIX: ${{ secrets.DOCKER_REGISTRY }}/restaurant-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build & Push All Services
        run: |
          declare -A services=(
            ["user-service"]=./user-service
            ["restaurant-service"]=./restaurant-service
            ["booking-service"]=./booking-service
            ["chat-service"]=./chat-service
            ["frontend-service"]=./frontend-service
          )

          for service in "${!services[@]}"; do
            context="${services[$service]}"
            image="$IMAGE_PREFIX/$service:latest"

            echo "Building $service"
            docker build -t "$image" "$context"

            echo "Pushing $image"
            docker push "$image"
          done

      - name: Install SSH Client and sshpass
        run: sudo apt-get install -y openssh-client sshpass

      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker compose pull
            docker compose down
            docker compose up -d --remove-orphans
          EOF
